/** False Nine roster positions, mapped from FPL element_type 1=GK/2=DEF/3=MID/4=FWD. */
export type Position = 'G' | 'D' | 'MD' | 'FW';

/**
 * Snapshot player — the contract between the ETL/model pipeline and the UI.
 * Projection fields (expected points, tiers, ceiling) land with the model slice;
 * this skeleton keeps the UI compiling against the committed placeholder snapshot.
 */
export type SnapshotPlayer = {
  id: string;
  name: string;
  position: Position;
  team: string;
};

/** data/snapshot.json — generated by `npm run etl`, committed, the UI's single data source. */
export type Snapshot = {
  generated_at: string;
  players: SnapshotPlayer[];
};
