/**
 * Canonical snapshot contract — the single source of truth shared by the ETL
 * (`src/etl/`) and the browser UI (`src/ui/`). `data/snapshot.json` is the
 * compiled artifact of these types.
 *
 * Settled with the modeling baseline in mind (docs/research/historical-baseline-modeling.md):
 * season stat lines are labeled and multi-season so the projection slice (#8)
 * can build per-90 rates and priors without reshaping this contract. The
 * FBref volume terms (SoT, KP, crosses, TklW, passes) will be *added* fields,
 * not a reshape.
 */

/** False Nine roster positions, mapped from FPL element_type 1=GKP/2=DEF/3=MID/4=FWD. */
export type Position = 'G' | 'D' | 'MD' | 'FW';

/** FPL availability status codes. */
export type PlayerStatus = 'a' | 'i' | 'd' | 's' | 'u' | 'n';

/**
 * One labeled FPL season for a player, from `element-summary/{id}.history_past`.
 * Most recent season first. Field set = the FPL-expressible subset of False Nine
 * scoring plus FPL's own points/xG/xA for cross-checks.
 */
export type SeasonStatLine = {
  /** FPL season label, e.g. "2025/26". */
  season: string;
  minutes: number;
  starts: number;
  goals: number;
  assists: number;
  cleanSheets: number;
  goalsConceded: number;
  saves: number;
  penaltiesSaved: number;
  /** FPL ships xG/xA as strings; null when absent for a season. */
  xg: number | null;
  xa: number | null;
  /** FPL fantasy points for the season — cross-check vs Underdog scoring, not a target. */
  fplPoints: number;
};

export type SnapshotPlayer = {
  /** FPL element id, stringified. */
  id: string;
  /** Display name (FPL `web_name`). */
  name: string;
  fullName: string;
  position: Position;
  /** FPL team short name, e.g. "MCI". */
  team: string;
  /** 2026/27 draft price in £m (FPL `now_cost` / 10). */
  price: number;
  status: PlayerStatus;
  /** FPL injury/availability news blurb; empty string when none. */
  news: string;
  /** Labeled prior seasons, most recent first. Empty for players with no FPL history. */
  seasons: SeasonStatLine[];
  /** Season-long False Nine projection (p10/p50/p90 + audit stat line), built
   *  by the model at snapshot time. Present on every player after ETL. */
  projection?: PlayerProjection;
};

export type SnapshotFixture = {
  id: number;
  /** Match week (FPL event). Round 1 of False Nine scores MW 1–26. */
  event: number;
  home: string;
  away: string;
  homeDifficulty: number;
  awayDifficulty: number;
  kickoff: string;
};

export type SnapshotMeta = {
  /** Players carrying at least one labeled season row. */
  playersWithHistory: number;
  positionCounts: Record<Position, number>;
};

import type { PlayerProjection } from '../model/types.js';

/** data/snapshot.json — generated by `npm run etl`, committed, the UI's single data source. */
export type Snapshot = {
  generated_at: string;
  meta: SnapshotMeta;
  players: SnapshotPlayer[];
  fixtures: SnapshotFixture[];
};
